name: Terraform validate

on:
  push:
    branches:
      - main
      - unify_refactoring
  pull_request:
    branches:
      - main

jobs:
  terraform-validate:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        tf_ver: [1.1.9,1.1.0,1.0.11,0.15.5,0.14.11]

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ matrix.tf_ver }}

    - name: Terraform Validate
      id: validate
      run: terraform validate
